"use client";

import * as React from "react";
import { Info } from "lucide-react";
import {
  Popover,
  PopoverTrigger,
  PopoverContent,
} from "@/components/ui/popover";
import { cn } from "@/lib/utils";

export interface AiMetricExplainerProps {
  type: "bias-distribution" | "bias-analysis" | "ai-summary" | "analysis-pending";
  className?: string;
  iconClassName?: string;
}

const EXPLAINER_DATA: Record<
  AiMetricExplainerProps["type"],
  { title: string; body: string; hint?: string }
> = {
  "bias-distribution": {
    title: "Bias Distribution",
    body: "Estimates the proportion of left-leaning, center, and right-leaning language, quotes, and framing detected across the article text.",
    hint: "Calculated across extracted article paragraphs and quoted sources.",
  },
  "bias-analysis": {
    title: "Bias Analysis",
    body: "The overall political framing label is determined by the dominant percentage and contextual confidence score. This represents an AI estimate, not objective editorial truth.",
    hint: "Scores range from -1.00 (Far Left) to +1.00 (Far Right).",
  },
  "ai-summary": {
    title: "AI Summary & Terms",
    body: "Synthesized key takeaways generated by Google Gemini. Loaded terms highlight emotionally charged or rhetorically slanted keywords identified in the text.",
    hint: "Generated automatically from clean, extracted article text.",
  },
  "analysis-pending": {
    title: "Analysis Pending",
    body: "This article is awaiting AI processing. Sentiment scores, political framing estimates, and key takeaways appear automatically once processed.",
    hint: "Analysis runs continuously via our scheduled pipeline.",
  },
};

export function AiMetricExplainer({
  type,
  className,
  iconClassName,
}: AiMetricExplainerProps) {
  const data = EXPLAINER_DATA[type];
  if (!data) return null;

  return (
    <Popover>
      <PopoverTrigger
        aria-label={`Explain ${data.title}`}
        className={cn(
          "inline-flex items-center justify-center text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-200 transition-colors p-0.5 rounded-full hover:bg-zinc-100 dark:hover:bg-zinc-800 outline-none cursor-pointer",
          className
        )}
      >
        <Info className={cn("h-3.5 w-3.5", iconClassName)} />
      </PopoverTrigger>
      <PopoverContent
        align="end"
        side="bottom"
        sideOffset={6}
        className="w-72 p-4 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 text-zinc-800 dark:text-zinc-200 shadow-xl rounded-xl space-y-2 z-50"
      >
        <div className="flex items-center gap-1.5 text-xs font-bold text-zinc-900 dark:text-zinc-100">
          <Info className="h-3.5 w-3.5 text-blue-500 shrink-0" />
          <span>{data.title}</span>
        </div>
        <p className="text-[12px] leading-relaxed text-zinc-600 dark:text-zinc-300 font-normal">
          {data.body}
        </p>
        {data.hint && (
          <div className="pt-2 border-t border-zinc-100 dark:border-zinc-800 text-[10px] text-zinc-400 font-medium">
            {data.hint}
          </div>
        )}
      </PopoverContent>
    </Popover>
  );
}
